local M = {}

local PIN_FILE = vim.fn.stdpath("config") .. "/lua/plugins/_pins.lua"

---@param days number
---@return string
local function get_date_ago(days)
	return days .. ".days.ago"
end

---@param plugin table
---@return string|nil
local function get_repo_dir(plugin)
	-- Use the plugin's installation directory if available
	if plugin.dir then
		return plugin.dir
	end
	return vim.fn.stdpath("data") .. "/lazy/" .. plugin.name
end

---@param url string
---@return string
local function normalize_url(url)
	-- Strip protocol and host, keep the path (owner/repo)
	-- Handles:
	--   https://github.com/owner/repo
	--   git@github.com:owner/repo.git
	--   https://codeberg.org/owner/repo
	local normalized = url:gsub("^https?://[^/]+/", ""):gsub("^git@[^:]+:", ""):gsub("%.git$", ""):gsub("/$", "")
	return normalized
end

M.pin_plugins = function(opts)
	opts = opts or {}
	local days = opts.days or 14
	local force_fetch = opts.force_fetch or false
	local date_ago = get_date_ago(days)

	local ok, lazy_config = pcall(require, "lazy.core.config")
	if not ok then
		vim.notify("Lazy.nvim config not found", vim.log.levels.ERROR)
		return
	end

	local pins = {}
	local total = 0
	local skipped = 0
	for _, plugin in pairs(lazy_config.plugins) do
		if plugin.url then
			if plugin.version or plugin.tag then
				skipped = skipped + 1
			else
				total = total + 1
			end
		end
	end

	local count = 0
	local spinner = require("lib.spinner").create({ global_var = "pin_spinner" })
	spinner.start()

	-- Sort names for consistent processing order
	local names = {}
	for name, _ in pairs(lazy_config.plugins) do
		table.insert(names, name)
	end
	table.sort(names)

	for _, name in ipairs(names) do
		local plugin = lazy_config.plugins[name]
		if plugin.url then
			if not (plugin.version or plugin.tag) then
				count = count + 1
				_G.pin_spinner_msg = string.format("Pinning %d/%d: %s", count, total, name)
				vim.cmd("redrawstatus")

				local repo_dir = get_repo_dir(plugin)
				if repo_dir and vim.fn.isdirectory(repo_dir) == 1 then
					-- Use the branch from spec, or try to detect it
					local branch = plugin.branch
					if not branch then
						local res =
							vim.system({ "git", "-C", repo_dir, "symbolic-ref", "--short", "refs/remotes/origin/HEAD" })
								:wait()
						if res.code == 0 then
							branch = res.stdout:gsub("^origin/", ""):gsub("%s+$", "")
						end
					end
					branch = branch or "main"

					if force_fetch then
						local fetch_res = vim.system({ "git", "-C", repo_dir, "fetch", "origin" }):wait()
						if fetch_res.code ~= 0 then
							vim.notify(
								string.format("Failed to fetch origin for %s: %s", name, fetch_res.stderr or "unknown error"),
								vim.log.levels.WARN
							)
						end
					end

					-- Find the commit older than N days
					local res = vim.system({
						"git",
						"-C",
						repo_dir,
						"rev-list",
						"-1",
						"--before=" .. date_ago,
						"origin/" .. branch,
					}):wait()

					local commit = ""
					if res.code == 0 then
						commit = res.stdout:gsub("%s+$", "")
					else
						vim.notify(
							string.format("Failed to resolve commit for %s: %s", name, res.stderr or "unknown error"),
							vim.log.levels.WARN
						)
					end

					if commit == "" then
						-- Fallback to latest commit if no commit found before date_ago
						local fallback_res = vim.system({
							"git",
							"-C",
							repo_dir,
							"rev-parse",
							"origin/" .. branch,
						}):wait()

						if fallback_res.code == 0 then
							commit = fallback_res.stdout:gsub("%s+$", "")
						else
							vim.notify(
								string.format(
									"Failed to resolve latest commit for %s: %s",
									name,
									fallback_res.stderr or "unknown error"
								),
								vim.log.levels.ERROR
							)
						end
					end

					if commit ~= "" then
						local url = plugin.url
						if url then
							table.insert(pins, { url = normalize_url(url), commit = commit, name = name })
						end
					end
				end
			end
		end
	end

	_G.pin_spinner_msg = nil
	spinner.stop()

	if #pins == 0 then
		vim.notify("No plugins to pin.", vim.log.levels.WARN)
		return
	end

	-- Write the pins file
	local lines = {
		"-- Auto-generated by :PinPlugins on " .. os.date("%Y-%m-%d"),
		"-- DO NOT EDIT MANUALLY. Run :PinPlugins to regenerate.",
		"",
		"return {",
	}

	for _, pin in ipairs(pins) do
		table.insert(lines, string.format('  { "%s", commit = "%s" },', pin.url, pin.commit))
	end
	table.insert(lines, "}")

	local f = io.open(PIN_FILE, "w")
	if f then
		f:write(table.concat(lines, "\n") .. "\n")
		f:close()
		local msg = "Pinned " .. #pins .. " plugins to commits older than " .. days .. " days."
		if skipped > 0 then
			msg = msg .. " (Skipped " .. skipped .. " plugins with version/tag constraints)"
		end
		vim.notify(msg, vim.log.levels.INFO)
	else
		vim.notify("Failed to write pins file: " .. PIN_FILE, vim.log.levels.ERROR)
	end
end

return M
